FF_CONFIGURE="--enable-gpl --enable-version3 --disable-debug --disable-runtime-cpudetect --disable-swscale-alpha  --disable-ffplay --disable-ffserver --disable-doc --disable-pixelutils --disable-faan --disable-fft --disable-rdft --disable-mdct --disable-lzo  --disable-lsp --disable-error-resilience --disable-dwt --disable-dct --disable-postproc --disable-d3d11va -disable-dxva2 --disable-vaapi --disable-vda --disable-vdpau --disable-everything --enable-encoder=libmp3lame --enable-demuxer=mp3 --enable-muxer=mp3 --disable-parsers --disable-indevs --disable-outdevs --disable-devices --disable-filters"
FF_CFLAGS=""
FF_CXXFLAGS=""
FF_LDFLAGS=""
GIT_BRANCH="master"
LICENSE_FILE="COPYING.GPLv3"
